import{i as c,S as m}from"./assets/vendor-5ObWk2rO.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&t(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function t(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const h="47064360-4b5ebf85b57e55ef7595b1100",g="https://pixabay.com/api/";function y(s){const r=new URLSearchParams({key:h,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15}),n=`${g}?${r.toString()}`;return fetch(n).then(t=>{if(!t.ok)throw new Error("...UPS");return t.json()}).then(t=>(console.log(t),t.hits.length===0?(c.error({title:"Помилка",message:"Вибачте, не знайдено зображень за вашим запитом. Спробуйте ще раз!",position:"topCenter",backgroundColor:"#ef4040"}),[]):t.hits)).catch(t=>{console.log(t),c.error({title:"Помилка",message:"Сталася помилка при отриманні даних. Спробуйте ще раз.",position:"topCenter",backgroundColor:"#ef4040"})})}const a=document.querySelector(".list");function b(s){const r=s.map(({webformatURL:n,largeImageURL:t,tags:e,likes:o,views:i,comments:p,downloads:d})=>`
        <div class="gallery-item">
            <a href="${t}">
                <img src="${n}" alt="${e}" width="360" height="200"/>
            </a>
            <div class="info">
                <p class="info-text"><b class="xz">Likes:</b> ${o}</p>
                <p class="info-text"><b class="xz">Views:</b> ${i}</p>
                <p class="info-text"><b class="xz">Comments:</b> ${p}</p>
                <p class="info-text"><b class="xz">Downloads:</b> ${d}</p>
            </div>
        </div>
    `).join("");a.innerHTML="",a.insertAdjacentHTML("beforeend",r)}const f=document.querySelector(".search-form"),L=document.querySelector(".search-form input"),u=document.querySelector(".loader");let l;f.addEventListener("submit",x);function x(s){s.preventDefault(),console.log("Працює чи нє");const r=L.value.trim();if(console.log(r),r==="")return c.info({position:"topRight",title:"Помилка",message:"Заповніть поле запиту"});S(),y(r).then(n=>{n&&n.length>0&&(b(n),l?l.refresh():l=new m(".gallery-item a",{captionsData:"alt",captionDelay:250}))}).catch(n=>{console.log(n),c.error({position:"topRight",title:"Помилка",message:"Сталася помилка при отриманні зображень. Спробуйте ще раз!",backgroundColor:"#ef4040"})}).finally(()=>{v(),f.reset()})}function S(){u.style.display="block"}function v(){u.style.display="none"}
//# sourceMappingURL=index.js.map
